# Generated by Django 4.0.6 on 2022-09-25 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=20)),
                ('tipo_empresa', models.CharField(choices=[('comerciante', 'Comerciante'), ('productor', 'Productor')], max_length=20)),
                ('margen_contribucion', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('c_v_u', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('p_v_u', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('participacion_ventas', models.DecimalField(decimal_places=3, max_digits=10)),
                ('margen_contribucion', models.DecimalField(decimal_places=3, max_digits=10)),
                ('empresa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinerApp.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('unidad_compra', models.CharField(max_length=30)),
                ('precio_compra', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unidades_utilizada', models.DecimalField(decimal_places=3, max_digits=10)),
                ('factor', models.DecimalField(decimal_places=3, max_digits=10)),
                ('producto_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='FinerApp.producto')),
            ],
        ),
    ]
