# Generated by Django 4.0.6 on 2022-10-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinerApp', '0006_rename_unidad_concepto_unidad_ultilizada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concepto',
            name='costo_variable',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='concepto',
            name='factor',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='concepto',
            name='precio_compra',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='concepto',
            name='unidad_ultilizada',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='c_v_u',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='margen_contribucion',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='p_v_u',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='participacion_ventas',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
