# Generated by Django 4.0.6 on 2022-10-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinerApp', '0007_alter_concepto_costo_variable_alter_concepto_factor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
