# Generated by Django 4.0.6 on 2022-09-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinerApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='margen_contribucion',
            new_name='margen_contribucion_negocio',
        ),
        migrations.RemoveField(
            model_name='concepto',
            name='unidades_utilizada',
        ),
        migrations.AddField(
            model_name='concepto',
            name='costo_variable',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='concepto',
            name='tipo_unidad',
            field=models.CharField(default='a', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concepto',
            name='unidad',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='concepto',
            name='factor',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
