# Generated by Django 4.0.6 on 2022-09-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinerApp', '0002_rename_margen_contribucion_empresa_margen_contribucion_negocio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='c_v_u',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='p_v_u',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
