# Generated by Django 4.0.6 on 2022-09-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinerApp', '0003_alter_producto_c_v_u_alter_producto_p_v_u'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='margen_contribucion',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
