# Generated by Django 4.0.6 on 2022-10-03 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinerApp', '0005_rename_nombre_concepto_nombreconcepto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concepto',
            old_name='unidad',
            new_name='unidad_ultilizada',
        ),
        migrations.RemoveField(
            model_name='concepto',
            name='tipo_unidad',
        ),
    ]
