# Generated by Django 4.0.6 on 2022-10-28 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FinerApp', '0006_rename_unidad_concepto_unidad_ultilizada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCosto', models.CharField(max_length=50)),
                ('valorCosto', models.DecimalField(decimal_places=1, max_digits=10)),
                ('empresa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinerApp.empresa')),
            ],
        ),
    ]
