# Generated by Django 4.0.6 on 2022-11-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinerApp', '0010_alter_concepto_costo_variable_alter_concepto_factor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cfu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diasLaboradosAnuales', models.DecimalField(decimal_places=1, max_digits=10)),
                ('jornadaDiara', models.DecimalField(decimal_places=1, max_digits=10)),
                ('empleadosParticipacion', models.DecimalField(decimal_places=1, max_digits=10)),
            ],
        ),
    ]
